### ISSUE TITLE
Import public domain comics to open access content server

### ISSUE THREAD

**Issue by courte** [NYPL-Simplified/content_server#17]
Leonard acquired several hundred gigs of public domain comic books from a site where people scan and share such comic books. This is a good test case for supporting access to works other than books.

To avoid bad feelings, making this entire collection available may require some negotiation with the site owners.

[Jira SIM-66](https://jira.nypl.org/browse/SIM-66)

**Comment by leonardr** [comment]
I'm closing this rather than moving it to the circulation manager like https://github.com/NYPL-Simplified/circulation/issues/909 for two reasons. First, comic books are very far off on our roadmap. Second, I think these particular comic books fall into the same chasm we found with Project Gutenberg books. There's so much stuff that nobody wants to read that it's bad librarianship to just dump the entire archive into SimplyE.

Unlike with public domain books, we don't have access to nicer curated collections, so this big archive could come back as a proof of concept, but I think it's safe to close this issue and revisit later.

Not even sure if I have this mirror anymore, now that the beastmachine is inaccessible...
