### ISSUE TITLE
Process Gutenberg titles in multiple languages.

### ISSUE THREAD

**Issue by courte** [NYPL-Simplified/content_server#30]
TODO: Some titles such as 44244 have titles in multiple languages. Not sure what to do about that.

This is commented on line 309 of `gutenberg.py`.

**Comment by leonardr** [comment]
The standard throughout the publishing world is that a book is in one language. Even for books where this makes no sense (such as a bilingual dictionary), a book has a single "language" and for some books you just have to pick one.

I applaud Project Gutenberg for bucking this trend in the name of strict accuracy, but we just can't store that data in our schema, and in practice it's turned out not to matter much. So the existing strategy (pick English if it's an option, otherwise pick the first one) is fine.
