### ISSUE TITLE
Standard Ebooks descriptions have been improved

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/content_server#83]
Following a conversation I had with Alex Cabal, the OPDS descriptions for Standard Ebooks books have been drastically improved, from the sentence-length summaries previously in the OPDS feed to high quality multi-paragraph descriptions. (These descriptions were previously present in the metadata inside the EPUBs, but not included in the OPDS.)

Forcing a full re-import of the Standard Ebooks OPDS feed should improve the descriptions of those books from the current (spotty) ones we get from OCLC.

**Comment by aslagle** [comment]
Since the updated tags in the OPDS feeds have changed, running the normal import script should take care of this.

**Comment by aslagle** [comment]
Once this is done and imported to the circ manager as well, we should check if 
https://circulation.librarysimplified.org/works/Standard%20Ebooks/URI/https://standardebooks.org/ebooks/robert-louis-stevenson/treasure-island/milo-winter is fixed. It currently has an id from gutenberg in the entry instead of standard ebooks.

**Comment by leonardr** [comment]
Either this has already been fixed or it will be fixed when I do a fresh import for the new NYPL content server.
